  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "email"
      PGADMIN_DEFAULT_PASSWORD: "pass"
    volumes:
      - path
    networks:
      - network-name
